### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by Count-Duckula-AU** [Rinnegatamante/smw-vita#1]
Thanks for another great release  :)

The game froze last night while playing 'coin collection' game mode, pretty sure I was on level '3blockforts'.
The music continued to play, but game had locked up with frozen display.

[psp2core-1549384235-0x0001362509-eboot.bin.psp2dmp.zip](https://github.com/Rinnegatamante/smw-vita/files/2835955/psp2core-1549384235-0x0001362509-eboot.bin.psp2dmp.zip)

**Comment by Rinnegatamante** [comment]
Thanks for the report, can you check if with this eboot you get still freezes?
[eboot.zip](https://github.com/Rinnegatamante/smw-vita/files/2837759/eboot.zip)

**Comment by Count-Duckula-AU** [comment]
Will play using the new eboot and let you know.

Just realised I must have hit cancel without thinking while it was writing the dump file (it has a .tmp extension). Sorry about that.

**Comment by afdc98** [comment]
With the new eboot.bin, I can safely say that the game hasn't crashed in half and hour of playtime, where the 0.9 release crashed within a few minutes in a game, though further testing may be required to check if it this crash is removed completely.

Good job with the release! ;) I really love this game, so thank you so much for porting it.

**Comment by Count-Duckula-AU** [comment]
I've also played for an hour or so with no further freezes, although I had played for at least 30 mins before the original beta release crashed. Will update if I have any further issues.
