### ISSUE TITLE
Game crashes with error C2-12828-1 on on start

### ISSUE THREAD

**Issue by spitfire** [Rinnegatamante/smw-vita#2]
Game crashes pretty much right after I start it on a Fat PSV running 3.60

**Comment by Rinnegatamante** [comment]
Install data files correctly.

**Comment by spitfire** [comment]
How should I do that? There is a zip file on vitadb, but no instructions.

**Comment by Rinnegatamante** [comment]
Extract the zip in data folder, same as all the other homebrews on VitaDB.
